---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../../../apps/monitoring/vmalert
components:
  - ../../../../../apps/monitoring/vmalert/components/tls-client-cert
  - ../../../../../apps/monitoring/vmalert/components/initcontainer-seed-rules
patches:
  - target:
      kind: Deployment
      name: vmalert
    patch: |
      - op: add
        path: "/spec/template/spec/containers/0/args"
        value:
          - "-notifier.url=http://router.dd.soeren.cloud:9093"
          - "-notifier.url=http://router.ez.soeren.cloud:9093"
          - "-datasource.url=https://victoriametrics.rs.soeren.cloud"
          - "-external.url=https://monitoring.svc.ez.soeren.cloud/vmalert/"
          - "-rule=/rules/*.rules"
