---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "openbao"
components:
  - "../../../../apps/openbao/components/istio"
resources:
  - "namespace.yaml"
  - "../../../../apps/openbao"
configMapGenerator:
  - name: "openbao"
    literals:
      - "BAO_DEV_ROOT_TOKEN_ID=test"
patches:
  - target:
      kind: "VirtualService"
      name: "openbao"
    patch: |-
      - op: "replace"
        path: "/spec/hosts"
        value:
          - "openbao.svc.dd.soeren.cloud"
