---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "vaultwarden"
resources:
  - "namespace.yaml"
  - "external-secret-restic.yaml"
  - "../../../../apps/vaultwarden"
components:
  - ../../../../apps/vaultwarden/components/istio
  - ../../../../apps/vaultwarden/components/pvc
  - ../../../../apps/vaultwarden/components/restic-sqlite
  - ../../../../infra/unrest/components/default-config
  - ../../../../infra/unrest/components/with-random-sleep
  - ../../../../infra/unrest/components/with-timezone-berlin
patches:
  - target:
      kind: "VirtualService"
      name: "vaultwarden"
    patch: |-
      - op: "replace"
        path: "/spec/hosts"
        value:
          - "vaultwarden.svc.dd.soeren.cloud"
configMapGenerator:
  - name: "vaultwarden"
    options:
      disableNameSuffixHash: true
    literals:
      - "DOMAIN=https://vaultwarden.svc.dd.soeren.cloud"
  - name: "vaultwarden-restic"
    options:
      disableNameSuffixHash: true
    literals:
      - "RESTIC_REPOSITORY=s3:https://s3.amazonaws.com/soerenschneider-restic-prod/vaultwarden"
      - "RESTIC_HOST=svc.dd.soeren.cloud"
