---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "nats"
resources:
  - "namespace.yaml"
  - "../../../../apps/nats"
components:
  - "../../../../apps/nats/components/istio"
patches:
  - target:
      kind: "VirtualService"
      name: "nats"
    patch: |-
      - op: "replace"
        path: "/spec/hosts"
        value:
          - "nats.svc.ez.soeren.cloud"
