---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: cicd
resources:
  - "repo-dns-ha.yaml"
  - "repo-fetcharr.yaml"
  - "repo-ip-plz.yaml"
  - "repo-sc.yaml"
  - "repo-sc-agent.yaml"
  - "repo-ssh-aegis.yaml"
  - "repo-tunnelguard.yaml"
