---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "immich"
components:
  - "../../../../apps/immich/components/istio"
  - "../../../../apps/immich/components/pgvector"
resources:
  - "namespace.yaml"
  - "../../../../apps/immich"
patches:
  - target:
      kind: "VirtualService"
      name: "immich"
    patch: |-
      - op: "replace"
        path: "/spec/hosts"
        value:
          - "immich.svc.ez.soeren.cloud"
