---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../../../apps/monitoring/victorialogs
components:
  - ../../../../../apps/monitoring/victorialogs/components/istio
  - ../../../../../apps/monitoring/victorialogs/components/pvc
  - ../../../../../apps/monitoring/victorialogs/components/vector
