---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "whoogle"
resources:
  - "namespace.yaml"
  - "../../../../apps/whoogle"
components:
  - "../../../../apps/whoogle/components/istio"
patches:
  - target:
      kind: "VirtualService"
      name: "whoogle"
    patch: |-
      - op: "replace"
        path: "/spec/hosts"
        value:
          - "whoogle.svc.ez.soeren.cloud"
configMapGenerator:
  - name: "whoogle-config"
    options:
      disableNameSuffixHash: true
    literals:
      - "WHOOGLE_ALT_RD=https://redlib.svc.ez.soeren.cloud"
      - "WHOOGLE_CONFIG_NEAR=DÃ¼sseldorf"
      - "WHOOGLE_CONFIG_COUNTRY=DE"
      - "WHOOGLE_CONFIG_LANGUAGE=German"
      - "WHOOGLE_CONFIG_THEME=dark"
