---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "redlib"
  labels:
    app.kubernetes.io/name: "redlib"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "redlib"
  strategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: "redlib"
        app.kubernetes.io/name: "redlib"
        app.kubernetes.io/component: "redlib"
        app.kubernetes.io/part-of: "redlib"
    spec:
      securityContext:
        runAsUser: 61234
        runAsGroup: 61234
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - name: "redlib"
          image: "quay.io/redlib/redlib:latest@sha256:dffb6c5a22f889d47d8e28e33411db0fb6c5694599f72cf740c912c12f5fc1c6"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 61234
            runAsGroup: 61234
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
                - "ALL"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
          ports:
            - containerPort: 8080
              name: "redlib"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "location"
          whenUnsatisfiable: "ScheduleAnyway"
