---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "gotify"
resources:
  - "namespace.yaml"
  - "../../../../apps/gotify"
components:
  - "../../../../apps/gotify/components/istio"
  - "../../../../apps/gotify/components/networkpolicy-hermes"
patches:
  - target:
      kind: "VirtualService"
      name: "gotify"
    patch: |-
      - op: "replace"
        path: "/spec/hosts"
        value:
          - "gotify.svc.ez.soeren.cloud"
