---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ../../../../infra/unrest-sqlite
patches:
  - target:
      kind: "CronJob"
      name: "unrest-backup-sqlite"
    patch: |
      - op: "test"
        path: "/spec/jobTemplate/spec/template/spec/volumes/3/name"
        value: "data"
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/spec/volumes/3/persistentVolumeClaim/claimName"
        value: "vaultwarden"
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/spec/containers/0/envFrom"
        value:
          - secretRef:
              name: "vaultwarden-restic"
              optional: true
          - configMapRef:
              name: "vaultwarden-restic"
              optional: true
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/metadata/labels/restic~1name"
        value: "vaultwarden"
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/spec/securityContext/runAsUser"
        value: 44413
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/spec/securityContext/runAsGroup"
        value: 44413
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/spec/securityContext/fsGroup"
        value: 44413
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/spec/containers/0/securityContext/runAsUser"
        value: 44413
      - op: "replace"
        path: "/spec/jobTemplate/spec/template/spec/containers/0/securityContext/runAsGroup"
        value: 44413
configMapGenerator:
  - name: "vaultwarden-restic"
    behavior: "merge"
    options:
      disableNameSuffixHash: true
    literals:
      - "RESTIC_SQLITE_FILE=/pvc-data/db.sqlite3"
