---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../../apps/vector
namespace: vector
configMapGenerator:
  - name: vector-config
    behavior: merge
    files:
      - sink.yaml
