---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "hass"
components:
  - "../../../../apps/hass/components/config"
  - "../../../../apps/hass/components/istio"
  - "../../../../apps/hass/components/pvc"
resources:
  - "namespace.yaml"
  - "../../../../apps/hass"
patches:
  - target:
      kind: "VirtualService"
      name: "hass"
    patch: |-
      - op: "replace"
        path: "/spec/hosts"
        value:
          - "hass.svc.ez.soeren.cloud"
configMapGenerator:
  - name: homeassistant-config
    files:
      - configuration.yaml
