---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: "NetworkPolicy"
      name: "victorialogs"
    patch: |-
      - op: add
        path: "/spec/ingress/0/from/-"
        value:
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "vector"
          podSelector:
            matchLabels:
              kubernetes.io/app.name: "vector"
